CREATE TABLE "GZGS_QN"."A_QYZT" 
   (    "NBXH" VARCHAR2(24 BYTE) NOT NULL ENABLE, 
    "ZCH" VARCHAR2(15 BYTE), 
    "QYMC" VARCHAR2(100 BYTE), 
    "ZS" VARCHAR2(100 BYTE), 
    "FDDBR" VARCHAR2(100 BYTE), 
    "ZCZB" NUMBER(18,4), 
    "BZ" VARCHAR2(3 BYTE), 
    "QYLX" VARCHAR2(4 BYTE), 
    "LXDH" VARCHAR2(24 BYTE), 
    "JYFW" VARCHAR2(4000 BYTE), 
    "CLRQ" DATE, 
    "NJJG" VARCHAR2(10 BYTE), 
    "NJND" VARCHAR2(4 BYTE), 
    "DJJG" VARCHAR2(6 BYTE), 
    "JYFS" VARCHAR2(4000 BYTE), 
    "YYRQ1" DATE, 
    "YYRQ2" DATE, 
    "XYDJ" VARCHAR2(1 BYTE), 
    "DJRQ" DATE, 
    "SFHMD" VARCHAR2(1 BYTE), 
    "QYBZ" VARCHAR2(1 BYTE), 
    "BY1" VARCHAR2(100 BYTE), 
    "BY2" VARCHAR2(80 BYTE), 
    "BY3" VARCHAR2(40 BYTE), 
    "MCLX" VARCHAR2(1 BYTE), 
    "HYDM" VARCHAR2(5 BYTE), 
    "GXDW" VARCHAR2(9 BYTE), 
    "QZJYFW" VARCHAR2(200 BYTE), 
    "YBJYFW" VARCHAR2(4000 BYTE), 
    "DZYX" VARCHAR2(100 BYTE), 
    "LCBZ" VARCHAR2(2 BYTE), 
    "FXD" VARCHAR2(4 BYTE), 
    "OPTYPE" VARCHAR2(4 BYTE), 
    "HZRQ" DATE DEFAULT to_date('1900-01-01','yyyy-mm-dd'), 
    "ZXRQ" DATE DEFAULT to_date('1900-01-01','yyyy-mm-dd'), 
    "DXRQ" DATE DEFAULT to_date('1900-01-01','yyyy-mm-dd'), 
    "VALI" VARCHAR2(2 BYTE), 
    "HYML" CHAR(1 BYTE), 
    "UNISCID" VARCHAR2(18 BYTE), 
    "YIEDISTRICT" VARCHAR2(6 BYTE), 
    "PROLOC" VARCHAR2(200 BYTE), 
    "INSERT_TIME" TIMESTAMP (6), 
    "UPDATE_TIME" TIMESTAMP (6), 
    "ZSXZQH" VARCHAR2(6 BYTE), 
     CONSTRAINT "A_QYZT_NBXH" PRIMARY KEY ("NBXH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GZGS_QN"  ENABLE, 
     SUPPLEMENTAL LOG GROUP "GGS_87609" ("NBXH") ALWAYS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 70909952 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GZGS_QN" ;

   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."NBXH" IS '内部序号';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."ZCH" IS '注册号';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."QYMC" IS '企业名称';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."ZS" IS '经营场所';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."FDDBR" IS '法定代表人';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."ZCZB" IS '注册资本';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."BZ" IS '币种';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."QYLX" IS '企业类型';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."LXDH" IS '联系电话';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."JYFW" IS '经营范围';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."CLRQ" IS '成立日期';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."NJJG" IS '年检结果';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."NJND" IS '年检年度';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."DJJG" IS '登记机关';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."JYFS" IS '经营方式';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."YYRQ1" IS '营业日期起';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."YYRQ2" IS '营业日期截止';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."XYDJ" IS '信用等级';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."DJRQ" IS '定级日期';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."SFHMD" IS '是否列入黑名单';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."QYBZ" IS '企业标示';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."BY1" IS '备用一(特殊行业标志)';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."BY2" IS '备用二(迁入备注)';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."BY3" IS '备用三(原注册号)';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."MCLX" IS '名称类型';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."HYDM" IS '行业代码';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."GXDW" IS '管辖单位';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."QZJYFW" IS '前置经营项目';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."YBJYFW" IS '一般经营项目';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."DZYX" IS '地址邮箱';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."LCBZ" IS '流程标志';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."FXD" IS '风险度';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."OPTYPE" IS '经营类别';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."UNISCID" IS '统一社会信用代码';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."YIEDISTRICT" IS '生产经营地所在行政区划';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."PROLOC" IS '生产经营地';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."INSERT_TIME" IS 'insert时间';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."UPDATE_TIME" IS 'update时间';
   COMMENT ON COLUMN "GZGS_QN"."A_QYZT"."ZSXZQH" IS '住所行政区划';